name: Perform Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci

  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: false

      - name: Install Deps
        run: pnpm i

      - name: Test
        run: pnpm run test --run --reporter=verbose

  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: false

      - name: Install Deps
        run: pnpm i

      - name: Build Package
        run: pnpm run build

  check-success:
    runs-on: ubuntu-latest
    needs: [Lint, Test, Build]
    if: success()
    outputs:
      was_successful: ${{ steps.check-success.outputs.was_successful }}
    steps:
      - name: Check if all jobs were successful
        id: check-success
        run: |
          echo "was_successful=true" >> $GITHUB_OUTPUT

  was-successful:
    runs-on: ubuntu-latest
    needs: [check-success]
    if: always()
    steps:
      - name: Was Successful
        run: |
          passed="${{ needs.check-success.outputs.was_successful }}"
          if [[ $passed == "true" ]]; then
            echo "All checks passed"
            exit 0
          else
            echo "Check(s) failed"
            exit 1
          fi
